import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/styles/globals.css'
import '@/styles/style.scss'
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <div className="py-24">
            {children}
          </div>
          <Toaster visibleToasts={1} position="bottom-right" richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
